version: "2"
project_name: semver

release:
  github:
    owner: pandeptwidyaop
    name: semver

builds:
  - id: build
    main: ./main.go
    binary: semver
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

