name: Go Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release with GoReleaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Auto Tagging
        run: |
          VERSION=$(date +"v%Y.%m.%d.%H%M")
          git tag $VERSION
          git push origin $VERSION

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sL https://git.io/goreleaser | bash

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --clean
